### ISSUE TITLE
docker-compose: Mount /tmp somewhere

### ISSUE THREAD

**Issue by rye** [hybsearch/hybsearch#110]
We should also include the stuff for bind-mounting the cache, so that the cache can persist between server reboots. We'll just need to make sure we clear it when we change the implementation for any steps.

(We should also drop to `version: '2'`, cuz that's what Ubuntu gives us.)

**Comment by hawkrives** [comment]
Done in e0ea941d54075e2dce3cd6abdd3df0fb9ec44447 and d5d0713a2466a86ee6b4b648a5bbee7c0ce4daba.
