### ISSUE TITLE
Automatically start the server process if it's not running

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#18]
so you don't need to remember to start it.

Should be sure to handle the case where Docker's not installed / not running.

**Comment by rye** [comment]
I would remark that this could be solved by just deploying our own server.  Still, a good idea.

**Comment by hawkrives** [comment]
I think it'd be nice for development – I tend to forget to start it…

**Comment by rye** [comment]
Something something #19?

**Comment by hawkrives** [comment]
Closing in favor of #19
