### ISSUE TITLE
Generate installable Windows / macOS app bundles

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#23]
And link to them from the README.

I was looking at using [`electron-builder`](https://www.electron.build).

Just something for our Bio people to make it easier to download for them to play with.

**Comment by hawkrives** [comment]
@OmarShehata If I'm dreaming, it would be nice to have Travis automatically build new binaries when a tag is pushed and attach them to the tag.

I can also work on that, myself.

**Comment by OmarShehata** [comment]
I could probably do that! I was using electron-forge but had trouble with that and it needed to restructure the directory so I just packaged the windows build manually. If we use Travis then it can generate binaries for both OS's.

**Comment by rye** [comment]
@hawkrives, this would be... nice.

We should consider folding `electron-builder` into the workflow, as you had mentioned.  Then, we can set window titles and make Electron actually use that metadata.

**Comment by OmarShehata** [comment]
Did you say this was done @hawkrives ?

**Comment by hawkrives** [comment]
Not yet.

**Comment by hawkrives** [comment]
oops, thanks

**Comment by hawkrives** [comment]
I think this is complete. Auto-update may be buggy, but that was never essential.
