### ISSUE TITLE
Account for hyphens in hammingDistance function

### ISSUE THREAD

**Issue by rye** [hybsearch/hybsearch#29]
We should make sure that the counter only gets incremented if there are two differing nuclotides; not just if two characters are different.  (If one is a `-` and the other is a base pair, blah blah blah.)

**Comment by mollysrour** [comment]
Fixed this, but having a hard time figuring out how to push the file back on to github with the changes

**Comment by hawkrives** [comment]
On your local computer, do `git checkout -b account-for-hyphens`, then do `git push -u origin account-for-hyphens` – that should push a new branch, which you should be able to make a pull request for with the Create Pull Request button on the Pull Requests tab of GitHub. 

We can also help you during the face to face meeting this afternoon.

**Comment by hawkrives** [comment]
Closed by #35
