### ISSUE TITLE
Move ent/nonmonophyly detection into data pipeline

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#31]
We'll need to be able to pass data back from the server process multiple times.

What we'll need to do:

| client | ⟺ | server
| --- | --- | ---
| reads file from disk | | |
| sends file to server | ⟹ | |
| | | if file is genbank, converts to fasta
| | | aligns sequences with clustal-omega
| | | converts fasta file to nexus format
| | | generates consensus tree with MrBayes
| | | converts consensus tree to Newick (PHYLIP) format
| | | encodes Newick tree as JSON structure
| | ⟸ | sends Newick tree to Electron (client) app
| renders phylogenetic tree | | analyses JSON newick tree for nonmonophyly with `ent`
| | ⟸ | sends list of nonmonomyletic identifiers to client app
| highlights nonmonophyletic sequences in red | |

Everything until the "analyses JSON newick tree for nonmonophyly with `ent`" bit is already done.

**Comment by OmarShehata** [comment]
This is done with https://github.com/hybsearch/hybsearch/pull/43
