### ISSUE TITLE
Exclude completely distinct genes from analysis (threshold of similarity)

### ISSUE THREAD

**Issue by rye** [hybsearch/hybsearch#37]

**Comment by OmarShehata** [comment]
Test on outpluscox1, the node with the largest number should be excluded.

**Comment by OmarShehata** [comment]
@mollysrour I just finished moving the code to the server, merging it with all the new updates, and it's much cleaner/easier to read now. You can find in the [prune-newick-outliers](https://github.com/hybsearch/hybsearch/tree/prune-newick-outliers) branch.

Specifically, if you go to [prune-newick.js](https://github.com/hybsearch/hybsearch/blob/prune-newick-outliers/server/lib/prune-newick.js) you'll find the code we came up with to remove things that are 2 standard deviations away. Can you take a crack at implementing the new approach Steve asked for in that file? (If the syntax of Javascript feels like it's getting in the way, feel free to implement it in R or something and I can just port it! He also sent us two files to test on, so feel free to add those to the data/ folder and test on them).

**Comment by mollysrour** [comment]
@hawkrives I think this was fixed by the pruned outliers algorithm that Omar and I created

**Comment by hawkrives** [comment]
@mollysrour I'll close it then!
