### ISSUE TITLE
Colorize lines of graph instead of/in addition to the dots?

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#41]
We think it would be nice to colorize the lines of the graph leading up to the nonmonophyletic docs, in addition to the dots themselves.

@hawkrives is not sure how to do this with what we have; someone with more d3 experience should probably take a look.

**Comment by rye** [comment]
I think this would be nice.  We can connect the dot with the lines themselves, to get a nice continuous appearance.  I can mess with this, but someone else who has more free time can feel free to do this.

**Comment by mollysrour** [comment]
Pr #61 addresses this
