### ISSUE TITLE
Fix alert-of-nonmonophyly when clicking a dot

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#42]
When you click a dot, you're supposed to get an `alert()` of the nonmonophyletic pair.

That is currently broken.

**Comment by rye** [comment]
It appears that the `onNodeClicked` function in `electron/graph.js` gets called, or should get called, but isn't getting called.

https://github.com/hybsearch/hybsearch/blob/9b06af0de3e001b794d63be319a14ab83221601e/electron/graph.js#L107-L120

Digging deeper, it seems that this is passed through to `d3.phylogram.js`, which differs from upstream a bit.

And, digging into that, I notice that the clicking handler is applied to the root node, but none of the other nodes?  I will make a branch for this.

**Comment by rye** [comment]
I added some work on [hs/hs:try-fix-clickability](https://github.com/hybsearch/hybsearch/tree/try-fix-clickability).

**Comment by hawkrives** [comment]
I'm not particularly attached to any of the graphing code; feel free to rewrite it if you wish. (Since most of it is just adding the nodes to D3, etc)
