### ISSUE TITLE
Homebrew removed beagle from their repos

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#5]
actually, they scrapped homebrew/science entirely

**Comment by hawkrives** [comment]
maybe https://github.com/Homebrew/homebrew-science/issues/6617

**Comment by sjackman** [comment]
Homebrew/science has been deprecated. The formulae in Homebrew/science have been archived at https://github.com/brewsci/homebrew-science. I've created a new tap for bioinformatics formulae at https://github.com/brewsci/homebrew-bio.
:beer: brew tap brewsci/bio
:beer: brew tap brewsci/science
:skull: brew untap homebrew/science

**Comment by sjackman** [comment]
Consider opening a pull request to submit `beagle` to https://github.com/brewsci/homebrew-bio

**Comment by rye** [comment]
This formula does exist [brewsci/homebrew-science](https://github.com/brewsci/homebrew-science/blob/master/Formula/beagle.rb), and we could just change the documentation.

A longer-term solution might be to vendor dependencies. (see #6)

**Comment by sjackman** [comment]
That's a just-fine interim measure. For the long haul, I'd encourage you to contribute `beagle` to https://github.com/brewsci/homebrew-bio. Let me know if you need any help with that. Or feel free to open a PR, and we can start the discussion there.

**Comment by rye** [comment]
We're just going to vendor this, I think. À la #3, which is a better long-term solution and will let us play downstream.

**Comment by hawkrives** [comment]
This is now closed; we're using beagle in Debian through Docker and a client/server model.

Thanks for the info, though, @sjackman!
