### ISSUE TITLE
Use/Implement Multi-Stage Build involving all of our dependencies

### ISSUE THREAD

**Issue by rye** [hybsearch/hybsearch#55]
In the Dockerfile, we install:

- clustalo
- mrbayes
  - (depends upon beagle-lib)
- seq-gen

We should vendor these from our forks.  The one question is: do we clone the repository in the build for Hybsearch? Or do we build separate images for each of these?

**Comment by rye** [comment]
For now, I will build everything in one big Multi-Stage build, and we can then just extract the various components out later.

**Comment by rye** [comment]
I think our long-term goal will probably (?) be to build these all together as separate images, installing them all from source, and then just copy the relevant files over from each.  This way, we can test/build each individual component separately.  I have yet to decide if that means we put the Dockerfile in our forks or if we make one big Dockerfiles repository for this purpose.

**Comment by hawkrives** [comment]
I guess it's fine if we just put the dockerfiles in each fork. Git's history means that we can always see exactly what changed in each repo.

**Comment by rye** [comment]
Closed by #86. Future work can get new issues.
