### ISSUE TITLE
Bug: seqmagick not found in :latest tag

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#56]
![untitled](https://user-images.githubusercontent.com/464441/37444103-fd1622b2-27dd-11e8-907f-56ae57b02c45.png)

reported by Steve

**Comment by hawkrives** [comment]
I need to check and see where `pip` installs things, and make sure it's actually getting installed I guess

**Comment by hawkrives** [comment]
This occurred because of #52, fwiw

**Comment by rye** [comment]
Well it's definitely not installed in `/usr/bin`—I just checked.  Could it be in `/usr/local/bin`?

**Comment by rye** [comment]
Yeah, it's in `/usr/local/bin`.

**Comment by rye** [comment]
![image](https://user-images.githubusercontent.com/1566689/37469718-ed8eba10-2833-11e8-91ad-101a3f780e81.png)
